---
title: "tnbc_r"
output: html_document
---


  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r libraries}
library(gridExtra)
library(grid)
# library(ggstance)
library(colorspace)
library(tidyverse)
library(dplyr)
library(readxl)
library(survival)
# install.packages('rms')
library(rms)
library(knitr)
library(rmdformats)
library(xtable)
library(ggplot2)
library(reticulate)

# options(xtable.floating = FALSE, xtable.timestamp = "", xtable.comment = FALSE)
# options(max.print="75")
# knitr::opts_chunk$set(echo=FALSE, cache=FALSE, prompt=FALSE,tidy=TRUE,
#                       comment=NA,message=FALSE,warning=FALSE)
# opts_knit$set(width=75)
```

```{r import data}
data <- read.csv(file="data_tnbc.csv")

temp <- subset(data, pTNM!= 'NA', select=c(RSI, pTNM, Event_OS, Time_OS, Event, Time, GARD))
temp$stage <- rep(NA, nrow(temp))
temp[temp$pTNM == 1 | temp$pTNM == 2, ][, "stage"] <- "low"
temp[temp$pTNM == 3, ][, "stage"] <- "high"
temp <- subset(temp, stage != 'NA')
# summary(as.factor(temp$pTNM))
# temp$Event_flipped <- rep(NA, nrow(temp))
# temp[temp$Event == 0, ][, "Event_flipped"] <- 1
# temp[temp$Event == 1, ][, "Event_flipped"] <- 0
temp$GARDneg = temp$GARD*(-1)

```


```{r ROC}
# library(ROCit)
# ROCit_gard <- rocit(score=temp$GARD,class=temp$Event_flipped)
# plot(ROCit_gard, values=F)
# summary(ROCit_gard)

# install.packages('PRROC')
# library(PRROC)
# PRROC_obj <- roc.curve(scores.class0 = temp$GARD, weights.class0=temp$Event, curve=TRUE)
# plot(PRROC_obj)

# sens_gard = nrow(subset(temp, GARD<22 & Event==1))/nrow(subset(temp, Event==1))
# spec_gard = nrow(subset(temp, GARD>22 & Event==0))/nrow(subset(temp, Event==0))

t=10
high_die = nrow(subset(temp, stage=='high' & Event_OS==1 & Time_OS<=t))
high_live = nrow(subset(temp, stage=='high')) - high_die
low_die = nrow(subset(temp, stage=='low' & Event_OS==1 & Time_OS<=t))
low_live = nrow(subset(temp, stage=='low')) - low_die
sens_tnm = high_die/(high_die + low_die)
spec_tnm = spec_tnm = low_live/(low_live + high_live)

myf<-function(x, x1=(1-spec_tnm), y1=sens_tnm, m=sens_tnm/(1-spec_tnm)){ 
  firstInds<-intersect(which(x >= 0), which(x < x1)) 
  secondInds<-intersect(which(x >= x1), which(x < 1))
  y<-x
  y[firstInds]<-m*x[firstInds]
  y[secondInds]<-((1-sens_tnm)*x[secondInds]+spec_tnm+sens_tnm-1)/spec_tnm
  y
}
x<-seq(0,1,0.01)
# plot(x, myf(x))
plot(x, myf(x), ylab="Sensitivity", xlab="1-Specificity", main="ROC at time t=10, AUC=62.0", col="white"); 
lines(x, myf(x), col="blue");
segments(x0=0,y0=0,x1=1,y1=1, lty=2)


# t = seq(1, floor(max(temp$Time)),1)
# sens_tnm = vector()
# spec_tnm = vector()
# for (i in t) {
#    high_recur = nrow(subset(temp, stage=='high' & Event==1 & Time<=t(i)))
#    high_lc = nrow(subset(temp, stage=='high')) - high_recur
#    low_recur = nrow(subset(temp, stage=='low' & Event==1 & Time<=t(i)))
#    low_lc = nrow(subset(temp, stage=='low')) - low_recur
#    sens_tnm(i) = high_recur/(high_recur + low_recur)
#    spec_tnm(i) = low_lc/(low_lc + high_lc)
# }

```


``` {r timeROC}
library('timeROC')
timeROC_gardOS <- timeROC(T=temp$Time_OS, delta=temp$Event_OS, marker=temp$GARDneg,
                  cause=1,weighting="marginal",
                  times=seq(0,11,0.5), #quantile(temp$GARD,probs=seq(0,1,0.05)), # c(12,24,36,48,60,72,84,96,108)
                  iid=TRUE)
plot(timeROC_gardOS, time= 1)
plot(timeROC_gardOS, time= 3)
plot(timeROC_gardOS, time= 5)
plot(timeROC_gardOS, time= 10)
plotAUCcurve(timeROC_gardOS,conf.int=TRUE,conf.band=TRUE)

timeROC_gardLC <- timeROC(T=temp$Time, delta=temp$Event, marker=temp$GARDneg,
                  cause=1,weighting="marginal",
                  times=seq(0,11,0.5), #quantile(temp$GARD,probs=seq(0,1,0.05)), # c(12,24,36,48,60,72,84,96,108)
                  iid=TRUE)
plot(timeROC_gardLC, time= 1)
plot(timeROC_gardLC, time= 3)
plot(timeROC_gardLC, time= 5)
plot(timeROC_gardLC, time= 10)
plotAUCcurve(timeROC_gardLC,conf.int=TRUE,conf.band=TRUE)

plotAUCcurveDiff(timeROC_gardOS, timeROC_gardLC)

# install.packages('survivalROC')
# library(survivalROC)

```

```{r staging}
library(Hmisc)
temp <- subset(data, pTNM!= 'NA', select=c(RSI, pTNM, Event_OS, Time_OS, Event, Time, GARD))
# temp$GARDneg = temp$GARD*(-1)

rcorr.cens(temp$GARD, Surv(temp$Time,temp$Event))
rcorr.cens(temp$pTNM, Surv(temp$Time,temp$Event))
rcorr.cens(temp$TNM_flipped, Surv(temp$Time,temp$Event))

nrow(subset(temp, pTNM==1 & GARD>=80))
histogram(~temp$GARD|temp$pTNM,layout=c(1,3),nint=20,scales=list(relation='free'),xlab="GARD",ylab="Percent of Patients within TNM Stage")

```


```{r 2 cutpoints packages}
library(here)
library(survival)
library(ggpubr)
library(survminer)
# library(patchwork)
library(rms) # for coxph function that has additional stats
library(stringr)
library(tidyverse)
```

# Load data and survival function
First we'll load the expression data from the `GSE48276` dataset. 
```{r load_data}
data <- read.csv(file="data_tnbc.csv")
temp <- subset(data, pTNM!= 'NA', select=c(RSI, pTNM, Event_OS, Time_OS, Event, Time, GARD))
temp2 <- subset(data, pTNM!= 'NA', select=c(RSI, pTNM, Event_OS, Time_OS, Event, Time, GARD))

#not really sure if this is relevant bc Jess's version uses it to make the GARD column
surv <- Surv(time = temp$Time, event = temp$Event) 
surv_os <- Surv(time = temp$Time_OS, event = temp$Event_OS) 
```

# Optimal Cutpoint Analysis
## Find optimal cutpoints
Next, we'll find sweep all cutpoint options to find the optimal cutpoint for three (`sweep_cutpoints2`) groups. 
```{r load_results}

sweep_cutpoints2 <- function(tidy_data, surv_obj){
   cutpoints_first = quantile(tidy_data$GARD, prob = seq(0, 1, 0.01))[-(1:5)]
   cutpoints_first = cutpoints_first[-(96:101)]
   cutpoint_first_vec <- c()
   cutpoint_second_vec <- c()
   low_n_vec <- c()
   middle_n_vec <- c()
   high_n_vec <- c()
   chisq_vec <- c()
   for (i in 1:length(cutpoints_first)){
      GARD_after_cutoff <- tidy_data$GARD[tidy_data$GARD > min(cutpoints_first)]
      cutpoints_second <- quantile(GARD_after_cutoff, prob = seq(0, 1, 0.01))[-(1:5)]
      cutpoints_second <- cutpoints_second[-(96:101)]
      for (j in 1:length(cutpoints_second)){
         tidy_data_labs <- tidy_data %>%
            mutate(pred_group = case_when(GARD <= cutpoints_first[i] ~ "low", 
                                          GARD > cutpoints_first[i] &
                                             GARD <= cutpoints_second[j] ~ "middle", 
                                          GARD > cutpoints_second[j] ~ "high"))
         survdiff_results <- survdiff(surv_obj ~ pred_group, data = tidy_data_labs)
         chisq_vec <- c(chisq_vec, survdiff_results$chisq)
         cutpoint_first_vec <- c(cutpoint_first_vec, cutpoints_first[[i]])
         cutpoint_second_vec <- c(cutpoint_second_vec, cutpoints_second[[j]])
         low_n_vec <- c(low_n_vec, nrow(tidy_data_labs %>% filter(pred_group == "low")))
         middle_n_vec <- c(middle_n_vec, nrow(tidy_data_labs %>% filter(pred_group == "middle")))
         high_n_vec <- c(high_n_vec, nrow(tidy_data_labs %>% filter(pred_group == "high")))
      }
   }
   data.frame(cutpoint1 = cutpoint_first_vec,
              cutpoint2 = cutpoint_second_vec,
              low_n = low_n_vec,
              middle_n = middle_n_vec,
              high_n = high_n_vec,
              chisq = chisq_vec) %>%
      rowwise() %>%
      mutate(min_n = min(low_n, middle_n, high_n)) %>%
      ungroup()
}

cutpoints <- sweep_cutpoints2(temp, surv_os)
cutpoints2 <- sweep_cutpoints2(temp2, surv)

cutpoints_filtered <- cutpoints %>%
   filter(min_n >= 4) %>% #require at least 4 samples in each group
   filter(chisq > 10) # == max(chisq)) #   #cutpoints with the highest chisq result

cutpoints_filtered2 <- cutpoints2 %>%
   filter(min_n >= 4) %>% #require at least 4 samples in each group
   filter(chisq > 10) # == max(chisq) #cutpoints with the highest chisq result

```


## Classify predictions
Now, we'll classify each of our samples as high, medium, or low. 
```{r classify predictions}

# LC
cutpoints_filtered2 <- cutpoints_filtered2[order(-cutpoints_filtered2$chisq),]
rank <- 1
double_cutpoint_best <- c(cut1 = cutpoints_filtered2[rank, ]$cutpoint1, 
                          cut2 = cutpoints_filtered2[rank, ]$cutpoint2)

lab1 = paste("GARD <",toString(trunc(10*cutpoints_filtered2[1, ]$cutpoint1)/10))
lab2 = paste("GARD ",toString(trunc(10*cutpoints_filtered2[1,]$cutpoint1)/10),"-",toString(trunc(10*cutpoints_filtered2[1, ]$cutpoint2)/10))
lab3 = paste("GARD >",toString(trunc(10*cutpoints_filtered2[1, ]$cutpoint2)/10))

temp2 <- temp2 %>%
      mutate(
          pred_3grp_tert2 = factor(case_when(GARD < quantile(GARD, 0.33) ~ "1_Low",
                                GARD >= quantile(GARD, 0.33) & GARD < quantile(GARD, 0.66) ~ "2_Middle",
                                GARD >= quantile(GARD, 0.66) ~ "3_High"),
                                ordered = TRUE),
          pred_3grp_optimal2 = case_when(GARD <= double_cutpoint_best["cut1"] ~ "1_Low",
                                GARD > double_cutpoint_best["cut1"] &
                                   GARD <= double_cutpoint_best["cut2"] ~ "2_Middle",
                                GARD > double_cutpoint_best["cut2"] ~ "3_High"),
          pred_3grp_25502 = factor(case_when(GARD < quantile(GARD, 0.25) ~ "1_Low",
                                GARD >= quantile(GARD, 0.25) &
                                   GARD < quantile(GARD, 0.75) ~ "2_Middle",
                                GARD >= quantile(GARD, 0.75) ~ "3_High"), 
                                ordered = TRUE))


# OS
df <- cutpoints_filtered[order(-cutpoints_filtered$chisq),]

# they all cut the data with the same samples in each group
# taking the first value to get a single value for each cutpoint
rank <- 1
double_cutpoint_best <- c(cut1 = df[rank, ]$cutpoint1, 
                          cut2 = df[rank, ]$cutpoint2)

lab1 = paste("GARD <",toString(trunc(10*df[rank, ]$cutpoint1)/10))
lab2 = paste("GARD ",toString(trunc(10*df[rank, ]$cutpoint1)/10),"-",toString(trunc(10*df[rank, ]$cutpoint2)/10))
lab3 = paste("GARD >",toString(trunc(10*df[rank, ]$cutpoint2)/10))
temp <- temp %>%
      mutate(
          pred_3grp_tert = factor(case_when(GARD < quantile(GARD, 0.33) ~ "1_Low",
                                GARD >= quantile(GARD, 0.33) & GARD < quantile(GARD, 0.66) ~ "2_Middle",
                                GARD >= quantile(GARD, 0.66) ~ "3_High"),
                                ordered = TRUE),
          pred_3grp_optimal = case_when(GARD <= double_cutpoint_best["cut1"] ~ "1_Low",
                                GARD > double_cutpoint_best["cut1"] &
                                   GARD <= double_cutpoint_best["cut2"] ~ "2_Middle",
                                GARD > double_cutpoint_best["cut2"] ~ "3_High"),
          pred_3grp_2550 = factor(case_when(GARD < quantile(GARD, 0.25) ~ "1_Low",
                                GARD >= quantile(GARD, 0.25) &
                                   GARD < quantile(GARD, 0.75) ~ "2_Middle",
                                GARD >= quantile(GARD, 0.75) ~ "3_High"), 
                                ordered = TRUE))
```


## Plot Results
```{r Optimal 3 group cutpoints}
# OS
km_tert_opt <- survfit(surv_os ~ temp$pred_3grp_optimal)
gg_grp3_opt <- ggsurvplot(km_tert_opt, data = temp, size = 1,
   conf.int = FALSE, # Add confidence interval
   pval = TRUE, # Add p-value
   risk.table = TRUE, # Add risk table
   risk.table.height = 0.25, # change if you have >2 groups
   risk.table.y.text.col = T, # show colors in table listing
   ncensor.plot = FALSE,
   ncensor.plot.height = 0.25,
   xlab = "Time in years", # adjust X axis label
   xlim = c(0, 18),
   break.time.by = 1, # break X axis in time intervals
   legend.labs = c(lab1, lab2, lab3), #c("Low GARD", "Middle GARD", "High GARD"),
   title = "TNBC OS grouped by GARD tertile (optimal)",
   ggtheme = theme_bw() + theme(plot.title = element_text(hjust = 0.5))
   )
gg_grp3_opt


# LC
km_tert_opt2 <- survfit(surv ~ temp$pred_3grp_optimal)
gg_grp3_opt2 <- ggsurvplot(km_tert_opt2, data = temp, size = 1,
   conf.int = FALSE, # Add confidence interval
   pval = TRUE, # Add p-value
   risk.table = TRUE, # Add risk table
   risk.table.height = 0.25, # change if you have >2 groups
   risk.table.y.text.col = T, # show colors in table listing
   ncensor.plot = FALSE,
   ncensor.plot.height = 0.25,
   xlab = "Time in years", # adjust X axis label
   xlim = c(0, 18),
   break.time.by = 1, # break X axis in time intervals
   legend.labs = c(lab1, lab2, lab3), #c("Low GARD", "Middle GARD", "High GARD"),
   title = "TNBC LC grouped by GARD tertile (optimal)",
   ggtheme = theme_bw() + theme(plot.title = element_text(hjust = 0.5))
   )
gg_grp3_opt2
```

```{r Tertiles by 33%}
km_tert_by33 <- survfit(surv_os ~ temp$pred_3grp_tert)
gg_grp3_tert <- ggsurvplot(km_tert_by33, data = temp, size = 1,
   conf.int = FALSE, # Add confidence interval
   pval = TRUE, # Add p-value
   risk.table = TRUE, # Add risk table
   risk.table.height = 0.25, # change if you have >2 groups
   risk.table.y.text.col = T, # show colors in table listing
   ncensor.plot = FALSE,
   ncensor.plot.height = 0.25,
   xlab = "Time in years", # adjust X axis label
   xlim = c(0, 18),
   break.time.by = 1, # break X axis in time intervals
   legend.labs = c("Low GARD", "Middle GARD", "High GARD"),
   title = "TNBC OS grouped by GARD tertile 33/33/33",
   ggtheme = theme_bw() + theme(plot.title = element_text(hjust = 0.5))
   )
gg_grp3_tert


km_tert_by33_2 <- survfit(surv ~ temp$pred_3grp_tert)
gg_grp3_tert2 <- ggsurvplot(km_tert_by33_2, data = temp, size = 1,
   conf.int = FALSE, # Add confidence interval
   pval = TRUE, # Add p-value
   risk.table = TRUE, # Add risk table
   risk.table.height = 0.25, # change if you have >2 groups
   risk.table.y.text.col = T, # show colors in table listing
   ncensor.plot = FALSE,
   ncensor.plot.height = 0.25,
   xlab = "Time in years", # adjust X axis label
   xlim = c(0, 18),
   break.time.by = 1, # break X axis in time intervals
   legend.labs = c("Low GARD", "Middle GARD", "High GARD"),
   title = "TNBC LC grouped by GARD tertile 33/33/33",
   ggtheme = theme_bw() + theme(plot.title = element_text(hjust = 0.5))
   )
gg_grp3_tert2
```

```{r Tertiles by 25/50/25}
km_tert_by25_50_25 <- survfit(surv_os ~ temp$pred_3grp_2550)
gg_grp3_2550 <- ggsurvplot(km_tert_by25_50_25, data = temp, size = 1,
   conf.int = FALSE, # Add confidence interval
   pval = TRUE, # Add p-value
   risk.table = TRUE, # Add risk table
   risk.table.height = 0.25, # change if you have >2 groups
   risk.table.y.text.col = T, # show colors in table listing
   ncensor.plot = FALSE,
   ncensor.plot.height = 0.25,
   xlab = "Time in years", # adjust X axis label
   xlim = c(0, 18),
   break.time.by = 1, # break X axis in time intervals
   legend.labs = c(lab1, lab2, lab3), #c("Low GARD", "Middle GARD", "High GARD"),
   title = "TNBC OS grouped by GARD, 25/50/25",
   ggtheme = theme_bw() + theme(plot.title = element_text(hjust = 0.5))
   )
gg_grp3_2550

km_tert_by25_50_25_2 <- survfit(surv ~ temp$pred_3grp_2550)
gg_grp3_2550_2 <- ggsurvplot(km_tert_by25_50_25_2, data = temp, size = 1,
   conf.int = FALSE, # Add confidence interval
   pval = TRUE, # Add p-value
   risk.table = TRUE, # Add risk table
   risk.table.height = 0.25, # change if you have >2 groups
   risk.table.y.text.col = T, # show colors in table listing
   ncensor.plot = FALSE,
   ncensor.plot.height = 0.25,
   xlab = "Time in years", # adjust X axis label
   xlim = c(0, 18),
   break.time.by = 1, # break X axis in time intervals
   legend.labs = c("Low GARD", "Middle GARD", "High GARD"),
   title = "TNBC LC grouped by GARD, 25/50/25",
   ggtheme = theme_bw() + theme(plot.title = element_text(hjust = 0.5))
   )
gg_grp3_2550_2
```

```{r Dose-GARD Distribution Comparison}
library(dplyr)

# # if source was different, could make y = Source
# ggplot(data, aes(x = GARD, y = factor(Event))) + 
#   geom_violin() + 
#   geom_boxplot(width = 0.1)


Limits <- unique(data$Site)%>%sort(decreasing = T)

gardplot <- ggplot(data) + theme(axis.text.y=element_blank(),axis.ticks.y=element_blank()) + xlim(0,80) +
  geom_boxplot(aes(x=GARD, y = 2), outlier.shape = NA) 
  geom_jitter(aes(x=GARD, y = 2), height = .15, size=08,alpha=.6)
 
  
tdplot <- ggplot(data) + theme(axis.text.y=element_blank(),axis.ticks.y=element_blank()) + xlim(0,80) +
  geom_boxplot(aes(x=TD), outlier.shape = NA) 
  geom_jitter(aes(x=TD), height = .15, size=0.8,alpha=.6)
  
library(patchwork)
tdplot / gardplot
  
```

```{r violin}
# install.packages("patchwork")
library(patchwork)


plot_gard <- ggplot(data, aes(x = GARD, y = 1)) + 
  geom_violin() + 
  geom_boxplot(width = 0.1) + 
  xlim(limits = c(0, 100))

plot_alpha <- ggplot(data, aes(x = alpha, y = 1)) + 
  geom_violin() + 
  geom_boxplot(width = 0.1) + 
  xlim(limits = c(0, 1))


plot_gard 
plot_alpha


```

```{r Cox}
library(rms)
f_LR<-cph(Surv(Time, Event) ~ GARD, data=data, x=T, y=T, surv = T)
p_LR<-Predict(f_LR, GARD = seq(1,80,by=1))
p_LR<-data.frame(p_LR)
# stats_HN <- summary.fit(f) 
#   rename('chi-sq' = chisq) %>%
f_OS<-cph(Surv(Time_OS, Event_OS) ~ GARD, data=data, x=T, y=T, surv = T)
p_OS<-Predict(f_OS, GARD = seq(1,80,by=1))
p_OS<-data.frame(p_OS)
  
ggplot(p_LR) + ggtitle("Local Control") + geom_line(aes(x=GARD,y=yhat), color = 'red') +
geom_abline(intercept=0, slope=0) +
geom_ribbon(aes(x=GARD,ymax=upper,ymin=lower, fill = 'red'), alpha=.2) + 
scale_x_continuous(expand = expansion(mult=0, add=0)) +
# facet_wrap(~Outcome, nrow = 1) +
xlab("GARD") + 
ylab("log Relative Hazard") +
theme_classic() +  theme(legend.position = "none")
theme(panel.border = element_rect(fill = rgb(1,1,1,0),size = .75))   # +
# geom_label(data = stats_HN,
#            fill = rgb(.5,.5,.5,.1), hjust="left",
#            size=2.4, label.r = unit(2,"points"),
#            label.size = 0, show.legend = FALSE,
#            aes(label = sprintf("Coef = %s \nChi-Sq = %s \nP = %.4f", coef, chisq, p), x=30, y=-2))

# fit<-cph(Surv(Time, Event) ~ rcs(GARD,3), data=data, x=T, y=T)
# fit.rcs<-fit
#stats_rec_rcs<-c(c(anova(fit)[c(1,3,4),1]),c(anova(fit)[c(1,3,4),3]))

# interaction_rec_rcs <- ggplot(p) + geom_line(aes(x=GARD,y=yhat,color=Received_RT), size=.4) +
#   geom_ribbon(aes(x=GARD,ymin=lower,ymax=upper,fill=Received_RT),alpha=.2) +
#   geom_vline(xintercept=cutpoint, size=.4, linetype='22') +
#   scale_y_continuous(expand = expansion(mult=0,add=0), limits=c(-4,3)) +
#   scale_x_continuous(expand = expansion(mult=0,add=0), 
#                      # minor_breaks = c(seq(5,80,by=5)), 
#                      limits = c(0,80)) + 
#   ylab("log Relative Hazard (First Recurrence)") + xlab("GARD") + 
#   theme_bw() +
#   

  
plotOS <- ggplot(p) + ggtitle("Overall Survival") + geom_line(aes(x=GARD,y=yhat), color = 'red') +
geom_abline(intercept=0, slope=0) +
geom_ribbon(aes(x=GARD,ymax=upper,ymin=lower, fill = 'red'), alpha=.2) +
scale_x_continuous(expand = expansion(mult=0, add=0)) +
# facet_wrap(~Outcome, nrow = 1) +
xlab("GARD") +
ylab("log Relative Hazard") +
theme_classic() + theme(legend.position = "none")
theme(panel.border = element_rect(fill = rgb(1,1,1,0),size = .75))
# 
# library(patchwork)
# 
# plotLR + plotOS
```
